### ISSUE TITLE
[FEAT] Main branch for stable jeedom version / Branche Main pour la version stable de Jeedom

### ISSUE THREAD

**Issue by Hotfirenet** [jeedom/core#2575]
Garder temporairement la branche stable-V4 mais faire en sorte que la version stable soit sur une branche du type Main ou Master ou RC.

Keep the stable-V4 branch temporarily but ensure that the stable version is on a branch like Main or Master or RC.

**Comment by rocket13011** [comment]
https://stackoverflow.com/questions/549920/is-it-possible-to-alias-a-branch-in-git/549949#549949

**Comment by pifou25** [comment]
C'est une bonne idée, mais la branche master existe déjà, il suffirait juste de merge / rebase V4-stable sur master non ?

Ensuite, si besoin créer un alias v4-stable, mais pourquoi voudrait-on faire cela ?

**Comment by rocket13011** [comment]
Dans les jeedom nous somme en V4-stable pour la branche il faut que le core des anciennes versions puissent ce mettre à jour.

**Comment by pifou25** [comment]
> Dans les jeedom nous somme en V4-stable pour la branche il faut que le core des anciennes versions puissent ce mettre à jour.

Ok dans ce cas il faudra garder la branche V4-stable, aussi longtemps qu'il restera des anciennes version à mettre à jour.

Mais on peut déjà switcher sur master :) 
l'alias de git (symbolic-ref) est une mauvaise piste ce n'est pas pris en charge sur github, ça n'affiche rien. A priori c'est juste pour un usage local.
Au pire, on peut faire un workflow qui met à jour V4-stable sur master...

**Comment by rocket13011** [comment]
Tu aurai la possibilité de le faire le workflow ?

**Comment by pifou25** [comment]
Voici un exemple qui déclenche sur une PR acceptée ou bien un push sur master. Je ne pense pas qu'il y a besoin d'un token spécifique, en principe le workflow peut écrire dans son propre repo avec le token par défaut.

```yaml
name: Auto Merge to V4-stable

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  merge-to-v4-stable:
    if: (github.event_name == 'pull_request' && github.event.pull_request.merged == true) || (github.event_name == 'push' && github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Merge to V4-stable
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch origin
          git checkout V4-stable
          git merge master --no-edit
          git push origin V4-stable
```
